- hosts: maven
  remote_user: ec2-user
  become: yes
  tasks:
    - name: install Docker
      yum:
        name: docker
        state: latest
      
    - name: Docker start
      service:
        name: docker
        state: started
    - name: app deploy
      copy: 
        src: ./Dockerfile
        dest: /dock/
        mode: '0777'
         
    - name: Image Build
      command: /dock/"docker build -t httpdimage ."
      args:
        chdir: /dock/
    - name: Container
      shell: /dock/"docker run -itd --name httpdcontainer -p 8090:80 httpdimage"
