- hosts: maven
  remote_user: ec2-user
  become: yes
  tasks:
    - name: install Docker
      yum:
        name: docker
        state: latest
      
    - name: Docker start
      service:
        name: docker
        state: started
    - name: Image Build
      shell: "docker build -t httpdimage"
    - name: Container
      shell: "docker run -itd --name httpdcontainer -p 8090:80 httpdimage"
