- hosts: maven
  remote_user: ec2-user
  become: yes
  tasks:
    - name: install httpd
      yum:
        name: "{{ item }}"
        state: latest
      loop:
        - httpd
        - docker

    - name: httpd start
      service:
        name: "{{ item }}"
        state: started
      loop:
        - httpd
        - docker
        
    - name: copy
      copy:
        src: ./index.html
        dest: /var/www/html/index.html
        mode: '0777'
